/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycallendar.pkg1.pkg0;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.standard.DateTimeAtCompleted;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static mycallendar.pkg1.pkg0.Logowanie.conn;
import static mycallendar.pkg1.pkg0.Logowanie.pst;

/**
 *
 * @author Bartek
 */
public class KalendarzFrame extends JFrame {

public Zajecia  zajecie[];
JTable table;
static int id;
    
   
    public KalendarzFrame(){}
    public KalendarzFrame(int id) throws SQLException  {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         String wyswietl = "SELECT zajecia.nazwa, zajecia.godzina, zajecia.data, zajecia.miejsce, zajecia.czasTrwania, zajecia.informacjeDodatkowe"
                    + " FROM zajecia, uzytkownicy_zajecia, uzytkownicy "
                    + "WHERE zajecia.id_zajecia = uzytkownicy_zajecia.id_zajecia "
                    + "AND uzytkownicy_zajecia.id_uzytkownika = uzytkownicy.id_uzytkownika "
                    + "AND uzytkownicy.id_uzytkownika = "+id+" ORDER BY `zajecia`.`data`, `zajecia`.`godzina` DESC";
            
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(wyswietl);
            int rowcount = 0;
            
            while (rs.next()) {
                ++rowcount;
                // Get data from the current row and use it
                
            }
            
            if (rowcount == 0) {
                System.out.println("No records found");
            }
            rs.beforeFirst();
            
            zajecie = new Zajecia[rowcount];
            int i=0;
            while(rs.next()){
                zajecie[i] = new Zajecia();
                zajecie[i].nazwa  = rs.getString("nazwa");
                
                Timestamp timestamp = rs.getTimestamp("data");
                zajecie[i].dzien=timestamp.getDay();
                zajecie[i].miesiac=timestamp.getMonth();
                zajecie[i].rok = timestamp.getYear()+1900;
                
                timestamp = rs.getTimestamp("godzina");
                zajecie[i].godzina  = timestamp.getHours();
                zajecie[i].minuta = timestamp.getMinutes();
                zajecie[i].miejsce = rs.getString("miejsce");
                zajecie[i].czasTrwania =rs.getInt("czasTrwania");
                zajecie[i].informacjeDodatkowe = rs.getString("informacjeDodatkowe");
                i++;
            }
            rs.close();
            stmt.close();
            conn.close();
           
            
            Object[] ColumnNames = {"Nazwa", "Godzina", "Data", "miejsce", "czasTrwania","informacjeDodatkowe"};
            Object[][] data = new Object[rowcount][6];
            
            for(int j=0; j<rowcount; j++)
            {
                
                data[j][0]=zajecie[j].nazwa;
                data[j][1]= Integer.toString(zajecie[j].godzina)+":"+Integer.toString(zajecie[j].minuta);
                data[j][2]= Integer.toString(zajecie[j].dzien)+"/"+Integer.toString(zajecie[j].miesiac)+"/"+Integer.toString(zajecie[j].rok);
                data[j][3]= zajecie[j].miejsce;
                data[j][4]= Integer.toString(zajecie[j].czasTrwania);
                data[j][5]= zajecie[j].informacjeDodatkowe;
            }
            DefaultTableModel tblModel = new DefaultTableModel(data, ColumnNames);
            tblModel.setColumnIdentifiers(ColumnNames);
            table = new JTable(tblModel);
            table.setBounds(25, 50, 400, 200);
            table.setRowHeight(10);
            JScrollPane scroll= new JScrollPane();
            scroll.setViewportView(table);
            repaint();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 400));
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Kalendarz");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 155, 44);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 452, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

     
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalendarzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalendarzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalendarzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalendarzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new KalendarzFrame(id).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(KalendarzFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
