/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycallendar.pkg1.pkg0;


import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Bartek
 */
public class Logowanie extends javax.swing.JFrame {
    static Connection conn = null;
   static String polaczenieURL = "jdbc:mysql://127.0.0.1/mycallendar?user=root";//db4free.net/mycallendar?user=sibrand132&password=100krotka";
   static String daneZBazy;       
   static PreparedStatement pst = null;
   private Statement stat;
   

    void zarejestruj(String login, String haslo)throws ClassNotFoundException
    { 
    try{
      
      String dodaj="INSERT INTO uzytkownicy (Login,Haslo) VALUES ('"+login+"', '"+haslo+"')";
      conn = DriverManager.getConnection(polaczenieURL);           
      Class.forName("com.mysql.jdbc.Driver");
      Statement stmt = conn.createStatement();
      stmt.executeUpdate(dodaj);
      JOptionPane.showMessageDialog(null, "Successfully registered");
      conn.close();
    }
    catch (SQLException e)
    {
        JOptionPane.showMessageDialog(null, "User exists");
    }  
   }
    
    
    int pobierzID(String login) throws SQLException, ClassNotFoundException
    {
            int id = 0;
            conn = DriverManager.getConnection(polaczenieURL);
             
            Statement stmt = conn.createStatement();
            String SQL = "SELECT * FROM uzytkownicy Where Login="+'\u0022'+login+'\u0022';
            ResultSet rs = stmt.executeQuery(SQL);
             
            while (rs.next()){
                id = rs.getInt("id_uzytkownika");
      
    }
        return id;
    }
    
    
    
   void zaloguj(String login, String haslo)throws ClassNotFoundException, SQLException
    { 
       ResultSet rs;
      String sql = "Select * from uzytkownicy Where Login=? and Haslo=?";
      conn = DriverManager.getConnection(polaczenieURL);  
      pst=conn.prepareStatement(sql);
      pst.setString(1, login);
      pst.setString(2, haslo);      
      Class.forName("com.mysql.jdbc.Driver");
      rs = pst.executeQuery();
      if(rs.next())
      {
          JOptionPane.showMessageDialog(null, "Successfully logged in");
          
      }
      else{
          JOptionPane.showMessageDialog(null, "Invalid Login or/and Password");
      }
      
      conn.close(); 

    }

    /**
     * Creates new form ZajeciaForm
     */
    public Logowanie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("My Callendar");

        jLabel3.setText("Login:");

        jLabel4.setText("Hasło:");

        jButton1.setText("Zaloguj się");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jCheckBox1.setText("Zarejestruj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                .addComponent(jPasswordField1)))
                        .addComponent(jButton1)
                        .addComponent(jCheckBox1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(9, 9, 9)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        boolean allGood=false;
        if(jCheckBox1.isSelected())
        {
            try {
                zarejestruj(jTextField1.getText(),jPasswordField1.getText());  
            } 
            catch (ClassNotFoundException ex) {}
        }
        else
        {
            try{
                try {
                    zaloguj(jTextField1.getText(),jPasswordField1.getText());
                    allGood=true;
                } catch (SQLException ex) {
                    Logger.getLogger(Logowanie.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            catch(ClassNotFoundException ex){}
        }
        if(allGood == true)
        {
            dispose();
            Panel panel = new Panel();
            try {
                panel.id=pobierzID(jTextField1.getText());
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Logowanie.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Logowanie.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.print(panel.id);
            panel.setVisible(true);
            
           
            
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logowanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
